### ISSUE TITLE
Remove gulp

### ISSUE THREAD

**Issue by unional** [unional/tslint-config-unional#24]
Depending on `gulp` for testing is not needed.

Try to come up with a solution to test the styles using test runner such as `ava`.

**Comment by NateKong** [comment]
I am new to gulp and I am not sure if I am understanding what is going on. It seems like `gulp` is just using `tslint` under the various configurations: index, standard, strict.

I feel like I am missing something. Is goal here is to remove `gulp` and install `ava`? Is running `tslint` on a set of folders an option? e.g. `$ tslint 'spec/**/*.ts'`

FYI
`ava` is a JS test runner that works with TS through `tsc` so you will have a JS an TS files. I have `ava` running on my fork. It will run the folder spec/ava through `$ npm test` but the tests have been altered and will need to be gone through.

**Comment by unional** [comment]
What I was thinking is to leverage test runner (such as `ava`) capability to produce that result for individual test cases. e.g. the end result would be:

```sh
10 tests passed, 2 failed

test "abc" failed: <message from tslint or tsc>
test "xyz" failed: <message from tslint or tsc>
```

Using `ava` might not be a good choice because AFAIK I can't invoke `ava` from code.
I mention it because that is the test runner I use most of the time.

But may be like you say, using `tslint` (and `tsc`, as it takes on some linting responsibilities such as `noUnusedLocals`) directly may be sufficient.

**Comment by unional** [comment]
I improved the glupfile to make the testing actually more powerful.

I can replace it with `@unional/fixture` in the future, but it is doing its job well enough right now so it is likely not necessary to change.
